name: Build

on:
  workflow_dispatch:
  push:
    # branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Caching build dependencies
      - name: Dev Bundle Cache
        id: cache-dev-bundle
        uses: actions/cache@v4
        with:
          key: ${{ vars.VALHEIM_VERSION }}
          path: /home/runner/dev-bundle

      # Populate build dependencies (if not cached)
      - name: Download Build Dependencies Bundle
        if: ${{ steps.cache-dev-bundle.outputs.cache-hit != 'true'}}
        run: |
          wget -O dev-bundle.zip ${{ secrets.VDC_DEV_BUNDLE }}${{ vars.VALHEIM_VERSION }}.zip
          unzip -qq dev-bundle.zip -d /home/runner/dev-bundle

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: LTS
      - name: Remove environment.props for workflow
        run: rm DiscordConnector/environment.props
      - name: Restore dependencies
        # Specifying the "GamePath" as our build dependency directory (cached)
        run: |
          dotnet restore /p:GamePath=/home/runner/dev-bundle -v n DiscordConnector.sln
          ls -l /home/runner/.nuget/packages
          ls -l /home/runner/.nuget/packages/litedb
      - name: Build
        # Specifying the "GamePath" as our build dependency directory (cached)
        run: dotnet build --no-restore /p:GamePath=/home/runner/dev-bundle -v n DiscordConnector.sln

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: DiscordConnector-artifact.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: "/home/runner/work/valheim-discordconnector/valheim-discordconnector/Packages/Thunderstore/*.zip"
          # The desired behavior if no files are found using the provided path.

          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 30
